# Generated by Django 5.1.4 on 2024-12-11 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSede', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FarmaciaDato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos', to='api_farmacia.farmacia')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('existencias', models.IntegerField()),
                ('concentracion', models.IntegerField()),
                ('marca', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=20)),
                ('formula', models.BooleanField(default=False)),
                ('periodicidad', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('farmacias', models.ManyToManyField(related_name='medicamentos', to='api_farmacia.farmacia')),
            ],
        ),
    ]
