# Generated by Django 5.1.4 on 2024-12-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_farmacia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentosList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('existencias', models.IntegerField()),
                ('concentracion', models.IntegerField()),
                ('nombreFarmacia', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('marca', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=20)),
                ('formula', models.BooleanField(default=False)),
                ('periodicidad', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Medicamentos',
        ),
    ]
