# Generated by Django 5.1.4 on 2024-12-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dateBirth', models.DateField()),
            ],
        ),
    ]
